import { injectStyleSheet } from '@/styles/createStyleSheet'

injectStyleSheet('chapter-header-organism-css', `
.chapter-header-empty-action{width:100%;display:flex;align-items:center;gap:11px;margin:12px 0 0;padding:11px 13px;border:1px dashed var(--border-strong);border-radius:12px;background:var(--bg-panel-alt);color:var(--text-primary);text-align:left;transition:.16s ease}
.chapter-header-empty-action:hover{border-color:var(--accent-purple);background:var(--accent-purple-soft)}
.chapter-header-empty-action>span:last-child{display:flex;flex-direction:column;gap:2px}.chapter-header-empty-action strong{font-size:13px}.chapter-header-empty-action small{color:var(--text-secondary);font-size:11px}
.chapter-header-empty-icon{width:32px;height:32px;flex:0 0 32px;display:grid;place-items:center;border-radius:9px;background:var(--accent-purple-soft);color:var(--accent-purple)}
.chapter-header-wrapper{margin-top:12px;overflow:hidden;border:1px solid var(--border);border-radius:14px;background:var(--bg-panel-alt)}
.chapter-header-topbar{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:10px 12px;border-bottom:1px solid var(--border);background:var(--bg-panel)}
.chapter-header-topbar>div:first-child{display:flex;align-items:baseline;gap:8px;min-width:0}.chapter-header-eyebrow{color:var(--text-secondary);font-size:10px;font-weight:700;letter-spacing:.06em;text-transform:uppercase}.chapter-header-model-name{overflow:hidden;font-size:12px;text-overflow:ellipsis;white-space:nowrap}
.chapter-header-actions{display:flex;align-items:center;gap:6px}.chapter-header-actions button,.chapter-header-card-footer button{display:inline-flex;align-items:center;gap:5px;padding:7px 9px;border:1px solid var(--border);border-radius:8px;background:var(--bg-panel);color:var(--text-secondary);font-size:11px}.chapter-header-actions button:hover{color:var(--accent-purple);border-color:var(--accent-purple)}.chapter-header-actions .chapter-header-remove-button:hover{color:var(--danger);border-color:var(--danger)}
.chapter-header-canvas{padding:18px 22px;background-color:var(--bg-panel);background-image:linear-gradient(var(--border) 1px,transparent 1px),linear-gradient(90deg,var(--border) 1px,transparent 1px);background-size:16px 16px}
.chapter-header-preview{width:min(100%,900px);margin:0 auto;display:flex;flex-direction:column;color:var(--text-primary)}.chapter-header-image-row{width:100%;display:flex;align-items:center}.chapter-header-image{display:block;max-width:100%}.chapter-header-image-placeholder{width:min(100%,240px);height:100%;min-height:54px;display:grid;place-items:center;align-content:center;gap:5px;border:1px dashed var(--border-strong);border-radius:9px;color:var(--text-muted);font-size:10px}.chapter-header-text{width:100%;margin:0;white-space:pre-wrap}
.chapter-header-editable-text{width:100%;min-height:1.25em;margin:0;padding:2px 5px;overflow:hidden;border:1px solid transparent;border-radius:6px;outline:none;resize:none;background:transparent;color:inherit;line-height:1.25;transition:.16s ease}.chapter-header-editable-text:hover{border-color:var(--border-strong)}.chapter-header-editable-text:focus{border-color:var(--accent-purple);background:var(--bg-panel)}
.chapter-header-hint{margin:0;padding:8px 12px;border-top:1px solid var(--border);color:var(--text-secondary);font-size:10px;text-align:center}
.chapter-header-overlay{position:fixed;inset:0;z-index:120;display:grid;place-items:center;padding:24px;background:rgba(19,17,26,.55);backdrop-filter:blur(5px)}.chapter-header-modal{width:min(980px,100%);max-height:calc(100vh - 48px);overflow:hidden;display:flex;flex-direction:column;border:1px solid var(--border);border-radius:18px;background:var(--bg-panel);box-shadow:0 24px 70px rgba(19,17,26,.26)}.chapter-header-modal-header{display:flex;justify-content:space-between;gap:20px;padding:20px 22px 16px;border-bottom:1px solid var(--border)}.chapter-header-modal-header h3{margin:4px 0;font-size:18px}.chapter-header-modal-header p{margin:0;color:var(--text-secondary);font-size:12px}.chapter-header-close-button{width:34px;height:34px;flex:0 0 34px;display:grid;place-items:center;border:1px solid var(--border);border-radius:9px;background:transparent;color:var(--text-secondary)}
.chapter-header-modal-body{overflow:auto;padding:18px 22px 22px}.chapter-header-modal-state{min-height:220px;display:grid;place-items:center;align-content:center;gap:7px;color:var(--text-secondary);text-align:center;font-size:12px}.chapter-header-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:14px}.chapter-header-card{overflow:hidden;border:1px solid var(--border);border-radius:13px;background:var(--bg-panel)}.chapter-header-card-preview{min-height:150px;display:flex;align-items:center;padding:16px;border-bottom:1px solid var(--border);background:var(--bg-panel-alt)}.chapter-header-card-footer{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:12px}.chapter-header-card-footer>div{min-width:0;display:flex;flex-direction:column;gap:3px}.chapter-header-card-footer strong{overflow:hidden;font-size:12px;text-overflow:ellipsis;white-space:nowrap}.chapter-header-card-footer span{color:var(--text-secondary);font-size:10px}.chapter-header-card-footer button{flex:0 0 auto;border-color:var(--accent-purple);color:var(--accent-purple)}
@media(max-width:720px){.chapter-header-topbar{align-items:flex-start;flex-direction:column}.chapter-header-canvas{padding:14px}.chapter-header-overlay{padding:10px}.chapter-header-modal{max-height:calc(100vh - 20px)}}
`)

export const chapterHeaderCss={emptyAction:'chapter-header-empty-action',emptyIcon:'chapter-header-empty-icon',wrapper:'chapter-header-wrapper',topbar:'chapter-header-topbar',eyebrow:'chapter-header-eyebrow',modelName:'chapter-header-model-name',actions:'chapter-header-actions',removeButton:'chapter-header-remove-button',canvas:'chapter-header-canvas',preview:'chapter-header-preview',imageRow:'chapter-header-image-row',image:'chapter-header-image',imagePlaceholder:'chapter-header-image-placeholder',text:'chapter-header-text',editableText:'chapter-header-editable-text',hint:'chapter-header-hint',overlay:'chapter-header-overlay',modal:'chapter-header-modal',modalHeader:'chapter-header-modal-header',closeButton:'chapter-header-close-button',modalBody:'chapter-header-modal-body',modalState:'chapter-header-modal-state',grid:'chapter-header-grid',card:'chapter-header-card',cardPreview:'chapter-header-card-preview',cardFooter:'chapter-header-card-footer'} as const
