import { injectStyleSheet } from '@/styles/createStyleSheet'

injectStyleSheet('chapter-footer-selector-css', `
.chapter-footer-selector__trigger{display:inline-flex;align-items:center;gap:7px;max-width:180px;height:32px;padding:0 10px;border:1px solid var(--border);border-radius:8px;background:transparent;color:var(--text-secondary);font-size:12px;cursor:pointer}.chapter-footer-selector__trigger span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.chapter-footer-selector__trigger:hover{border-color:var(--border-strong);color:var(--text-primary)}
.chapter-footer-selector__overlay{position:fixed;inset:0;z-index:100;display:grid;place-items:center;padding:22px;background:rgba(19,17,26,.54);backdrop-filter:blur(5px)}.chapter-footer-selector__modal{width:min(860px,100%);max-height:calc(100vh - 44px);display:flex;flex-direction:column;overflow:hidden;border:1px solid var(--border);border-radius:20px;background:var(--bg-panel);box-shadow:0 24px 80px rgba(17,13,31,.24)}
.chapter-footer-selector__header{display:flex;justify-content:space-between;gap:24px;padding:20px 22px;border-bottom:1px solid var(--border)}.chapter-footer-selector__header h2{margin:0;font-size:20px}.chapter-footer-selector__header>div>p:last-child{margin:5px 0 0;color:var(--text-secondary);font-size:12px}.chapter-footer-selector__eyebrow{margin:0 0 4px!important;color:var(--accent-purple)!important;font-size:11px!important;font-weight:800;text-transform:uppercase;letter-spacing:.08em}.chapter-footer-selector__close{width:34px;height:34px;display:grid;place-items:center;border:1px solid var(--border);border-radius:10px;background:var(--bg-panel-alt);color:var(--text-secondary)}
.chapter-footer-selector__content{min-height:260px;padding:20px 22px;overflow:auto}.chapter-footer-selector__list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:15px}.chapter-footer-selector__card{position:relative;display:flex;align-items:center;gap:13px;width:100%;padding:15px;text-align:left;border:1px solid var(--border);border-radius:var(--radius-lg);background:var(--bg-panel-alt);color:var(--text-primary);cursor:pointer}.chapter-footer-selector__card:hover{transform:translateY(-1px);border-color:var(--border-strong)}.chapter-footer-selector__card--active{border-color:var(--accent-purple);box-shadow:0 0 0 2px var(--accent-purple-soft)}.chapter-footer-selector__icon{flex:0 0 auto;width:42px;height:42px;display:grid;place-items:center;border:1px solid var(--border-strong);border-radius:10px;background:var(--accent-purple-soft);color:var(--accent-purple)}.chapter-footer-selector__info{min-width:0;display:flex;flex-direction:column;gap:4px}.chapter-footer-selector__info strong{font-size:13px}.chapter-footer-selector__info small{color:var(--text-secondary);font-size:11px}.chapter-footer-selector__check{position:absolute;top:10px;right:10px;width:22px;height:22px;display:grid;place-items:center;border-radius:50%;background:var(--accent-purple);color:#fff}
.chapter-footer-selector__note{display:flex;flex-direction:column;gap:7px;margin-top:18px;padding:16px;border:1px solid var(--border);border-radius:var(--radius-lg);background:var(--bg-panel-alt)}.chapter-footer-selector__note>span{font-size:12px;font-weight:700}.chapter-footer-selector__note textarea{width:100%;min-height:76px;resize:vertical;padding:10px 11px;border:1px solid var(--border-strong);border-radius:9px;background:var(--bg-panel);color:var(--text-primary);font:inherit;font-size:12px;line-height:1.5;outline:none}.chapter-footer-selector__note textarea:focus{border-color:var(--accent-purple);box-shadow:0 0 0 3px var(--accent-purple-soft)}.chapter-footer-selector__note small{color:var(--text-secondary);font-size:10px;line-height:1.5}
.chapter-footer-selector__empty{min-height:220px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:8px;color:var(--text-secondary);text-align:center}.chapter-footer-selector__empty strong{color:var(--text-primary)}.chapter-footer-selector__empty span{max-width:330px;font-size:12px}.chapter-footer-selector__footer{display:flex;justify-content:flex-end;gap:8px;padding:14px 22px;border-top:1px solid var(--border)}.chapter-footer-selector__footer button{height:38px;display:inline-flex;align-items:center;justify-content:center;gap:7px;padding:0 14px;border-radius:9px;font-size:12px;font-weight:700}.chapter-footer-selector__footer button:disabled{opacity:.45;cursor:not-allowed}.chapter-footer-selector__secondary{border:1px solid var(--border);background:var(--bg-panel-alt);color:var(--text-secondary)}.chapter-footer-selector__secondary-action{border:1px solid var(--border-strong);background:var(--bg-panel);color:var(--text-primary)}.chapter-footer-selector__primary{border:1px solid var(--accent-purple);background:var(--accent-purple);color:#fff}
@media(max-width:700px){.chapter-footer-selector__list{grid-template-columns:1fr}.chapter-footer-selector__footer{flex-wrap:wrap}.chapter-footer-selector__footer button{flex:1 1 auto}}
`)

export const chapterFooterSelectorCss = {
  trigger:'chapter-footer-selector__trigger', overlay:'chapter-footer-selector__overlay', modal:'chapter-footer-selector__modal',
  header:'chapter-footer-selector__header', eyebrow:'chapter-footer-selector__eyebrow', close:'chapter-footer-selector__close',
  content:'chapter-footer-selector__content', list:'chapter-footer-selector__list', card:'chapter-footer-selector__card',
  cardActive:'chapter-footer-selector__card chapter-footer-selector__card--active', icon:'chapter-footer-selector__icon',
  info:'chapter-footer-selector__info', check:'chapter-footer-selector__check', noteField:'chapter-footer-selector__note',
  empty:'chapter-footer-selector__empty', footer:'chapter-footer-selector__footer', secondary:'chapter-footer-selector__secondary',
  secondaryAction:'chapter-footer-selector__secondary-action', primary:'chapter-footer-selector__primary',
} as const
