import { injectStyleSheet } from '@/styles/createStyleSheet'

injectStyleSheet('timeline-page-css', `
.timeline-page{display:grid;gap:20px}.timeline-page__header{display:flex;justify-content:space-between;gap:24px}.timeline-page__header h1{margin:2px 0 6px;font-size:24px}.timeline-page__header p{margin:0;max-width:720px;color:var(--text-secondary);font-size:13px;line-height:1.6}.timeline-page__eyebrow{margin:0;color:var(--accent-purple)!important;font-size:10px!important;font-weight:800!important;letter-spacing:.08em;text-transform:uppercase}
.timeline-page__tabs{display:flex;gap:6px;padding:5px;border:1px solid var(--border);border-radius:12px;background:var(--bg-panel-alt)}.timeline-page__tab{padding:9px 13px;border:0;border-radius:8px;background:transparent;color:var(--text-secondary);font-size:11px;font-weight:700}.timeline-page__tab--active{background:var(--bg-panel);color:var(--accent-purple);box-shadow:0 3px 12px rgba(25,20,40,.07)}
.timeline-page__panel{display:grid;gap:22px;padding:22px;border:1px solid var(--border);border-radius:var(--radius-lg);background:var(--bg-panel)}.timeline-page__section-header{display:flex;align-items:flex-start;justify-content:space-between;gap:20px;padding-bottom:18px;border-bottom:1px solid var(--border)}.timeline-page__section-header h2{margin:2px 0 5px;font-size:19px}.timeline-page__section-header p{margin:0;color:var(--text-secondary);font-size:12px}.timeline-page__ai{display:inline-flex;align-items:center;gap:7px;min-height:38px;padding:0 14px;border:1px solid var(--accent-purple);border-radius:9px;background:var(--accent-purple);color:white;font-size:11px;font-weight:800}
.timeline-page__chapters{display:grid;gap:10px}.timeline-page__chapter{display:grid;grid-template-columns:42px minmax(0,1fr) 18px;align-items:center;gap:11px}.timeline-page__order,.timeline-page__suggested-order{display:grid;place-items:center;width:40px;height:40px;border:1px solid var(--accent-purple);border-radius:11px;background:var(--accent-purple-soft);color:var(--accent-purple);font-size:10px;font-weight:800}.timeline-page__chapter-card{padding:13px 15px;border:1px solid var(--border);border-radius:11px;background:var(--bg-panel-alt)}.timeline-page__chapter-card small{color:var(--accent-purple);font-size:9px;font-weight:800;text-transform:uppercase}.timeline-page__chapter-card h3{margin:4px 0 5px;font-size:13px}.timeline-page__chapter-card p{margin:0;color:var(--text-secondary);font-size:10px;line-height:1.5}.timeline-page__arrow{color:var(--text-muted)}
.timeline-page__analysis{display:grid;gap:15px;padding:18px;border:1px solid var(--border);border-radius:14px;background:var(--bg-panel-alt)}.timeline-page__analysis>header{display:flex;justify-content:space-between;gap:16px}.timeline-page__analysis h3{margin:2px 0 0;font-size:15px}.timeline-page__analysis>header span{display:flex;align-items:center;gap:5px;color:var(--text-secondary);font-size:9px}.timeline-page__overview{margin:0;color:var(--text-secondary);font-size:11px;line-height:1.65}.timeline-page__suggestions{display:grid;gap:8px}.timeline-page__suggestions article{display:grid;grid-template-columns:40px 1fr;gap:11px;padding:11px;border:1px solid var(--border);border-radius:10px;background:var(--bg-panel)}.timeline-page__suggestions strong{display:block;font-size:12px}.timeline-page__suggestions small{display:block;margin:2px 0 5px;color:var(--accent-purple);font-size:9px}.timeline-page__suggestions p{margin:0;color:var(--text-secondary);font-size:10px;line-height:1.5}
.timeline-page__story-overview{display:flex;gap:12px;padding:15px;border:1px solid var(--border);border-radius:12px;background:var(--accent-purple-soft);color:var(--accent-purple)}.timeline-page__story-overview strong{font-size:12px}.timeline-page__story-overview p{margin:5px 0 0;color:var(--text-secondary);font-size:11px;line-height:1.6}.timeline-page__story{display:grid}.timeline-page__story article{position:relative;display:grid;grid-template-columns:54px 18px 1fr;gap:11px;padding-bottom:18px}.timeline-page__story article:not(:last-child)::before{content:'';position:absolute;left:62px;top:15px;bottom:0;width:1px;background:var(--border-strong)}.timeline-page__year{display:grid;justify-items:end}.timeline-page__year span{color:var(--text-muted);font-size:8px;text-transform:uppercase}.timeline-page__year strong{font-size:18px}.timeline-page__dot{position:relative;z-index:1;width:12px;height:12px;margin-top:7px;border:3px solid var(--accent-purple);border-radius:50%;background:var(--bg-panel)}.timeline-page__event{padding:14px;border:1px solid var(--border);border-radius:12px;background:var(--bg-panel-alt)}.timeline-page__event small{color:var(--accent-purple);font-size:9px;font-weight:800;text-transform:uppercase}.timeline-page__event h3{margin:4px 0 6px;font-size:13px}.timeline-page__event p{margin:0;color:var(--text-secondary);font-size:10px;line-height:1.6}
.timeline-page__empty{min-height:300px;display:grid;place-items:center;align-content:center;gap:9px;text-align:center}.timeline-page__empty>span{display:grid;place-items:center;width:58px;height:58px;border-radius:18px;background:var(--accent-purple-soft);color:var(--accent-purple)}.timeline-page__empty h3,.timeline-page__empty p{margin:0}.timeline-page__empty p{max-width:480px;color:var(--text-secondary);font-size:12px;line-height:1.6}.timeline-page__empty button{display:flex;align-items:center;gap:7px;margin-top:5px;padding:10px 14px;border:1px solid var(--accent-purple);border-radius:9px;background:var(--accent-purple);color:white;font-size:11px;font-weight:800}
.timeline-analysis__overlay{position:fixed;inset:0;z-index:100;display:grid;place-items:center;padding:22px;background:rgba(19,17,26,.54);backdrop-filter:blur(5px)}.timeline-analysis__modal{width:min(620px,100%);overflow:hidden;border:1px solid var(--border);border-radius:20px;background:var(--bg-panel);box-shadow:0 24px 80px rgba(17,13,31,.24)}.timeline-analysis__header{display:flex;justify-content:space-between;gap:20px;padding:20px 22px;border-bottom:1px solid var(--border)}.timeline-analysis__header h2{margin:2px 0 5px;font-size:19px}.timeline-analysis__header p{margin:0;color:var(--text-secondary);font-size:11px;line-height:1.5}.timeline-analysis__header button{width:34px;height:34px;display:grid;place-items:center;border:1px solid var(--border);border-radius:10px;background:var(--bg-panel-alt);color:var(--text-secondary)}.timeline-analysis__content{padding:20px 22px}.timeline-analysis__info{display:grid;gap:4px;padding:14px;border:1px solid var(--border);border-radius:11px;background:var(--bg-panel-alt)}.timeline-analysis__info strong{font-size:12px}.timeline-analysis__info span{color:var(--text-secondary);font-size:10px}.timeline-analysis__error{margin:12px 0 0;color:var(--danger);font-size:11px}.timeline-analysis__footer{display:flex;justify-content:flex-end;gap:8px;padding:15px 22px;border-top:1px solid var(--border)}.timeline-analysis__footer button{min-height:36px;padding:0 13px;border-radius:9px;font-size:11px;font-weight:800}.timeline-analysis__cancel{border:1px solid var(--border);background:var(--bg-panel-alt);color:var(--text-secondary)}.timeline-analysis__run{display:flex;align-items:center;gap:7px;border:1px solid var(--accent-purple);background:var(--accent-purple);color:white}
@media(max-width:700px){.timeline-page__section-header{flex-direction:column}.timeline-page__chapter{grid-template-columns:42px 1fr}.timeline-page__arrow{display:none}.timeline-page__story article{grid-template-columns:44px 16px 1fr}.timeline-page__story article:not(:last-child)::before{left:51px}}
`)

export const timelinePageCss = {
  page:'timeline-page',pageHeader:'timeline-page__header',eyebrow:'timeline-page__eyebrow',tabs:'timeline-page__tabs',
  tab:'timeline-page__tab',tabActive:'timeline-page__tab timeline-page__tab--active',panel:'timeline-page__panel',
  sectionHeader:'timeline-page__section-header',aiButton:'timeline-page__ai',chapterTimeline:'timeline-page__chapters',
  chapterItem:'timeline-page__chapter',orderBadge:'timeline-page__order',chapterCard:'timeline-page__chapter-card',arrow:'timeline-page__arrow',
  analysisResult:'timeline-page__analysis',overview:'timeline-page__overview',suggestionList:'timeline-page__suggestions',
  suggestedOrder:'timeline-page__suggested-order',storyOverview:'timeline-page__story-overview',storyTimeline:'timeline-page__story',
  yearColumn:'timeline-page__year',timelineDot:'timeline-page__dot',eventCard:'timeline-page__event',empty:'timeline-page__empty',
  overlay:'timeline-analysis__overlay',modal:'timeline-analysis__modal',modalHeader:'timeline-analysis__header',
  modalContent:'timeline-analysis__content',analysisInfo:'timeline-analysis__info',error:'timeline-analysis__error',
  modalFooter:'timeline-analysis__footer',cancel:'timeline-analysis__cancel',run:'timeline-analysis__run',
} as const
